### ISSUE TITLE
[Bug] Radar creates another hand slot when equipping

### ISSUE THREAD

**Issue by Desempregago** [ImExoOdeex/SupplementaryAccessories#2]
Plus it stays even after removing it from the slot (you can see the "experience" tooltip on the left)

https://user-images.githubusercontent.com/14002834/168939437-8de5c95d-6086-4751-90d4-d7e6ec37c202.mp4

**Comment by Desempregago** [comment]
![image](https://user-images.githubusercontent.com/14002834/168939783-dc4af16b-fac6-4bf4-a69a-619bf746aa4a.png)

**Comment by Desempregago** [comment]
I'm using Supplementary Accessories 1.1.0

**Comment by ImExoOdeex** [comment]
well, actually it was planned to add slot when you put _informational_ item in wrist slot. On second ss I can see empty slots, that's because you unequipped the item in wrong order (When you equip items, you must unequip items in opposite order you equipped). Try putting only one same item once in this slot. When tooltip stays on screen try put in and unequip one more time. Of course, you can wear multiple informational items, but when you put same item more than one left text will bug, and you will need to unequip and equip again to fix that. thanks for reporting <3

**Comment by ImExoOdeex** [comment]
Actual bug is that left text sometimes stays on screen - I need to fix it. With these empty slots after radar I have nothing, because it's Trinkets thing.

**Comment by ImExoOdeex** [comment]
just released a new version - now informational items don't create new slot and implemented new method to check is item equipped
